name: Build

on:
  pull_request:
  push:
    paths:
      - src/**
      - test/**

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - run: npm install
    - run: npm run all
